Feat/passenger service
DeVit1210/cab-aggregator-app pull request #1
Opened 2024-01-29 19:36 UTC by DeVit1210

1. CRUD for Passenger entity
2. Global exception handling using @RestControllerAdvice
3. Entity migrations with liquibase
4. Entity mapping with MapStruct
5. Validation
6. Pagination and sorting

2024-01-30 11:35 UTC, IvanKiselevichWork requested changes

2024-01-30 11:35 UTC, IvanKiselevichWork commented on pom.xml
> +    <modules>
Не нужно делать мультимодульный проект, каждый микросервис должен быть самостоятельным проектом. Но для удобства лучше хранить все сервисы в одном репозитории, как у тебя сейчас и сделано.

2024-01-30 11:35 UTC, IvanKiselevichWork commented on passenger-service/.gitignore
> +HELP.md
Это файл должен быть в корне репозитория

2024-01-30 11:35 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passenger/constants/MessageTemplates.java
> +    String PASSENGER_NOT_FOUND_BY_ID = "Passenger with id %s was not found!";
Обычно литералы с сообщениями об ошибках хранят в ресурсных файлах, и используют enum с ключом сообщения внутри, на случай добавления других языков.

2024-01-30 11:35 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passenger/exception/ApiException.java
> +public class ApiException {
Почему этот эксепшн ни от чего не наследуется?

2024-01-30 11:35 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passenger/exception/MultipleApiException.java
> +public class MultipleApiException {
Тот же вопрос про наследование

2024-01-30 11:35 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passenger/model/Passenger.java
> +
Лишние пустые строки

2024-01-30 12:14 UTC, DeVit1210 commented on passenger-service/src/main/java/com/modsen/passenger/exception/ApiException.java
> +public class ApiException {
Это как dto, только для эксепшнов

Когда какой-то эксепшн бросается, в @ExceptionHandler методе создается объект ApiException (сообщение об ошибке, ResponseStatus и timestamp) и отправляется клиенту, чтобы была одинаковая структура ответа от сервера при ошибке

2024-01-30 12:15 UTC, DeVit1210 commented on passenger-service/src/main/java/com/modsen/passenger/exception/MultipleApiException.java
> +public class MultipleApiException {
То же, что и ApiException, только здесь список сообщений об ошибке внутри (может быть полезно при обработке экспешнов из Hibernate Validation, там несколько ошибок может быть за 1 раз)

2024-01-31 09:03 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passenger/exception/ApiException.java
> +public class ApiException {
Тогда лучше переименовать этот класс, типа ApiExceptionMessage

2024-01-31 14:15 UTC, IvanKiselevichWork approved these changes

2024-01-31 14:25 UTC, merged