Feat/driver service
DeVit1210/cab-aggregator-app pull request #2
Opened 2024-02-01 11:27 UTC by DeVit1210

1. CRUD for Driver entity
2. Global exception handling using @RestControllerAdvice
3. Entity migrations with liquibase
4. Entity mapping with MapStruct
5. Validation
6. Pagination and sorting
7. Setup future communication with ride-service via Kafka

2024-02-05 16:02 UTC, przhevvalsky requested changes

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/pom.xml
> +        </dependency>
а зачем тебе зависимость spring-integration-kafka и spring-kafka, это ведь два разных подхода к интергации с кафкой?
по твоему коду ты используешь spring-kafka, зачем тянуть тогда integration?

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/dto/request/DriverRequest.java
> +    @NotEmpty(message = ValidationConstants.FIRST_NAME_NOT_EMPTY)
для такой строки " ", @NotEmpty не спасает. Попробуй @NotBlank

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/dto/request/RideRequest.java
> +    @NotEmpty(message = ValidationConstants.ID_NOT_EMPTY)
в доке написано вот для для аннотации @NotEmpty

![image](https://github.com/DeVit1210/cab-aggregator-app/assets/159006477/c2b47cdf-82c3-4420-95da-2b585ea29436)

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/exception/handler/DriverControllerAdvice.java
> +    public ResponseEntity<ApiExceptionInfo> handlePassengerNotFoundException(DriverNotFoundException e) {
название поправь

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/mapper/DriverMapper.java
> +@Mapper(componentModel = "spring")
можно через константу - MappingConstants.ComponentModel.SPRING, либо же просто SPRING

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/service/impl/DriverServiceImpl.java
> +        List<Driver> driverList = driverRepository.findAll();
есть у хибера один механизм - dirty checking. представь что у тебя этих драйверов миллионы, следовательно все они попадут в персистентный контекст хибера, и следовательно мы заставляем dirty checking бегать по всему миллиону и смотреть, а не изменилась ли наша сущность. зачем лишний раз нагружать систему, когда нам нужно только вывести этих драйверов. если есть желание посмотри как можно, минуя персистентный контекс, достать всех драйверов.

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/service/impl/DriverServiceImpl.java
> +        driver.setLicenceNumber(driverRequest.getLicenceNumber());
можно эту работу делегировать мапперу

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/service/impl/DriverServiceImpl.java
> +        }
suggestion - тернарником не хочется воспользоваться?)

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
представь ситуацию, что по какой-то случайности таблица была уже создана - у тебя будет выскакивать ошибка.
Решить это дело можно с помощью preCondidtion. В каких-то моментах это может покзаться избыточным, но всё же знать о таких вещах нужно)

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
> +                    type="enum('AVAILABLE', 'OFFLINE', 'ON_TRIP', 'WAITING_FOR_PASSENGER', 'DRIVING_FOR_PASSENGER')">
есть ли в этом профит прописывать значения енамов сюда?
просто, на мой взгляд, это сыграет злую шутку в том случае, если ты захочешь добавить какой-то новый статус, то кроме того, что тебе надо в самом енаме его добавить так ещё и написать новую миграцию для этого дела)

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
> +        </createTable>
не вижу роллбеков, если считаешь что они не нужны, то опиши почему

2024-02-05 16:02 UTC, przhevvalsky commented on driver-service/src/main/resources/db/changelog/v-1.0/db.changelog-v.1.0.xml
как тебе идея создать папку changesets в папке v-1.0, куда сложить все свои скрипты, за исключением аккумулирующего?

2024-02-05 16:16 UTC, DeVit1210 commented on driver-service/pom.xml
> +        </dependency>
Изначально хотел попробовать Spring Integration, но решил отложить на потом, не заметил, что не убрал зависимость

2024-02-05 16:17 UTC, DeVit1210 commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
> +                    type="enum('AVAILABLE', 'OFFLINE', 'ON_TRIP', 'WAITING_FOR_PASSENGER', 'DRIVING_FOR_PASSENGER')">
тоже думал над этим
получается, сделать просто type=enum?

2024-02-05 16:17 UTC, DeVit1210 commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
> +        </createTable>
Забыл, поправлю)

2024-02-05 16:20 UTC, przhevvalsky commented on driver-service/pom.xml
> +        </dependency>
не знаю лично как у вас, но вроде попробовать spring integration обязательно нужно, имей это в виду)

2024-02-05 16:45 UTC, DeVit1210 commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.xml
> +                    type="enum('AVAILABLE', 'OFFLINE', 'ON_TRIP', 'WAITING_FOR_PASSENGER', 'DRIVING_FOR_PASSENGER')">
Насколько знаю, в mysql нельзя создать enum, не указав списка его значений, т.е. type=enum не сработает.
Что тогда делать?
Альтернативой вижу сделать поле типа VARCHAR, но тогда содержимое чейнджлогов не будет совпадать с описанием сущностей в hibernate

2024-02-06 10:20 UTC, przhevvalsky requested changes

2024-02-06 10:20 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/constants/MappingConstants.java
> +}
не, такая константа уже существует у мапстракта, поэтому не надо дублировать код
вот - 
![image](https://github.com/DeVit1210/cab-aggregator-app/assets/159006477/daf15286-9960-4a7e-9e05-39573fb17d19)

2024-02-06 10:20 UTC, przhevvalsky commented on driver-service/src/main/java/com/modsen/driver/service/impl/DriverServiceImpl.java
>          return driverMapper.toDriverResponse(updatedDriver);
1. у тебя есть вроде как уникальные поля, но проверку типо 'водитель с таким phoneNumber уже существует' ты не делаешь 
2. у мапстракта есть такая возможность полностью скопировать значения полей из одного объекта в другой, так же и ты можешь сделать.

2024-02-07 07:40 UTC, przhevvalsky approved these changes

2024-02-07 07:47 UTC, merged